"""add_recording_url_to_calls

Revision ID: a722dd32a956
Revises: e8d837e23d3d
Create Date: 2026-09-04 16:53:29.404069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a722dd32a956'
down_revision: Union[str, None] = 'e8d837e23d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('recording_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'recording_url')
    # ### end Alembic commands ###
